-- erp-core initial schema + seed (Postgres). On the zero-infra H2 profile this
-- file is NOT run; JPA creates the schema and DataSeeder inserts the same rows.

CREATE TABLE IF NOT EXISTS customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(64) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    price_cents BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status      VARCHAR(32) NOT NULL DEFAULT 'POSTED',
    total_cents BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_order_lines (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    item_id          BIGINT NOT NULL,
    quantity         INTEGER NOT NULL DEFAULT 1,
    unit_price_cents BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS accounts (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  VARCHAR(32) NOT NULL UNIQUE,
    name  VARCHAR(255) NOT NULL,
    type  VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS journal_entries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT,
    account_id   BIGINT NOT NULL,
    description  VARCHAR(255),
    amount_cents BIGINT NOT NULL DEFAULT 0,
    entry_type   VARCHAR(16) NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --- seed data -------------------------------------------------------------
INSERT INTO customers (name, email) VALUES
    ('Acme Corporation', 'ap@acme.example'),
    ('Globex LLC',       'billing@globex.example'),
    ('Initech Inc',      'accounts@initech.example');

INSERT INTO items (sku, name, price_cents) VALUES
    ('SKU-1001', 'Standard Widget',   1999),
    ('SKU-1002', 'Premium Widget',    4999),
    ('SKU-2001', 'Enterprise License',99900),
    ('SKU-3001', 'Support Plan (yr)', 29900),
    ('SKU-4001', 'Onboarding Service',15000);

INSERT INTO accounts (code, name, type) VALUES
    ('1000', 'Cash',              'ASSET'),
    ('1100', 'Accounts Receivable','ASSET'),
    ('4000', 'Sales Revenue',     'REVENUE');
