-- V2: Accounts Payable — ADDITIVE ONLY. Safe to apply on an existing V1 database.
--
-- This migration only CREATEs new tables and INSERTs the AP control account.
-- It does NOT alter or drop any V1 object, so existing customers / items /
-- sales_orders / journal_entries rows are untouched. Because nothing existing
-- changes shape, pre-AP application code keeps running against this schema —
-- which is what makes a forward-safe CODE rollback after the update safe.

CREATE TABLE IF NOT EXISTS vendors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255),
    terms       VARCHAR(64),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id   BIGINT NOT NULL,
    status      VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    total_cents BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id           BIGINT NOT NULL,
    item_id         BIGINT,
    description     VARCHAR(255),
    quantity        INTEGER NOT NULL DEFAULT 1,
    unit_cost_cents BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_po_vendor ON purchase_orders (vendor_id);
CREATE INDEX IF NOT EXISTS idx_po_line_po ON purchase_order_lines (po_id);

-- AP control account (idempotent — accounts.code is UNIQUE).
INSERT INTO accounts (code, name, type)
VALUES ('2000', 'Accounts Payable', 'LIABILITY')
ON CONFLICT (code) DO NOTHING;
